### ISSUE TITLE
Encode JSON and display Image

### ISSUE THREAD

**Issue by mxmtsk** [serverfireteam/rapyd-laravel#14]
Hello,

in my table column I have a JSON saved for my uploaded image.

`{"url":"http://lorem.ipsum/dolor.jpeg","filename":"lorem-ipsum.jpeg","mimetype":"image/jpeg","size":115018,"id":1,"key":"club_gallery/16-07-28/4lOn0S9QSYy8X17tfOj8_37-lorem-ipsum.jpeg","container":"wtcfilepicker","client":"computer","isWriteable":true}`

Is it possible to encode the json in the data grid and display the img in an image container? If not, how could I add this functionality?

**Comment by quant-algo** [comment]
you need to add new data filed and send a pull request
