### ISSUE TITLE
Buttons not working 

### ISSUE THREAD

**Issue by pastebimas** [serverfireteam/rapyd-laravel#5]
Hey, I found bug.

rapyd-laravel/views/toolbar.blade.php 

just update this file with original rapyd file, because: 
$this->edit->link("/panel/photos/all","Grįžti", "BR"); such commands are not working. Fixed it when changing to

<code>
@if ( 
    (isset($label) && strlen($label)) || 
    (isset($buttons_left) && count($buttons_left)) || 
    (isset($buttons_right) && count($buttons_right))
    )
    <div class="btn-toolbar" role="toolbar">

```
    @if (isset($label) && strlen($label))
        <div class="pull-left">
            <h2>{!! $label !!}</h2>
        </div>
    @endif
    @if (isset($buttons_left) && count($buttons_left))
        <div class="pull-left">
            @foreach ($buttons_left as $button) {!! $button !!}
            @endforeach
        </div>
    @endif
    @if (isset($buttons_right) && count($buttons_right))
        <div class="pull-right">
            @foreach ($buttons_right as $button) {!! $button !!}
            @endforeach
        </div>
    @endif
</div>
<br />
```

@endif
</code>

**Comment by serverfire** [comment]
@pastebimas for me with is not working that code , could send pull request ?

**Comment by quant-algo** [comment]
please update to last version
