### ISSUE TITLE
Personalisation of wysiwyg editor

### ISSUE THREAD

**Issue by jbajou** [serverfireteam/rapyd-laravel#6]
Hello,

I was just wondering where I can change the default fonts, etc and options of the wysiwyg editor. Basically, I need to make sure it doesn't add any font-family style directive to the written text.

Thanks in advance!

**Comment by quant-algo** [comment]
@jbajou  you can edit this file in public/packages/zofe/rapyd/assets/tinymce/tinymce_editor.js and change the editor config

**Comment by jbajou** [comment]
lovely. Thanks for your help @serverfire
