### ISSUE TITLE
tags input with no database request for populating

### ISSUE THREAD

**Issue by jbajou** [serverfireteam/rapyd-laravel#7]
Hello,

Is there a way to use the input tags functionality as a tag selection for a blog post, which means that tags are not stored anywhere at the moment of typing ?

I would like to have a tag displayed each time the user press enter (as in your example codes) or tab (preferred way).

Thanks

**Comment by quant-algo** [comment]
@jbajou for that you have to create new filed type , it is very easy thing to do  , send pull request when you have done that
